------------------------------------------------------------------
------------------------------------------------------------------
------------------------------------------------------------------
-- Run with sysorclpdb
------------------------------------------------------------------
------------------------------------------------------------------
------------------------------------------------------------------

CREATE TABLE PASSPORT.passport(
  id integer GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1),
  residentId integer,


  passportID varchar(8),
  startDate Date, -- dd-MM-YYYY
  endDate Date, -- dd-MM-YYYY
  PRIMARY KEY(id)
);

CREATE TABLE PASSPORT.userRequest(
  id integer GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  locationId integer,


passportId varchar(8),
fullName varchar(255),
gender varchar(6) check (
    gender in ('Male', 'Female', 'None')
),
CCCD varchar(12),
phone varchar(11),
email varchar(255),

  extendDuration integer, --year that user want to extend
  isAuthenticated NUMBER(1, 0) DEFAULT 0,
  isApprove NUMBER(1, 0) DEFAULT 0,
  isRejected NUMBER(1, 0) DEFAULT 0,
  note varchar(255),
  
  PRIMARY KEY(id)
);

CREATE TABLE PASSPORT.resident (
  id integer GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  locationId integer,


  fullName varchar(255),
  gender varchar(6) check(gender in ('Male', 'Female', 'None')),
  CCCD varchar(12),
  phone varchar(11),
  email varchar(255),
  
  PRIMARY KEY(id)
);

CREATE TABLE PASSPORT.employee (
  id integer GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  residentId integer,


  username varchar(255),
  password varchar(255),
  role  varchar(10) CHECK(role in('BPXacThuc', 'BPXetDuyet', 'BPLuuTru', 'BPGiamSat')),
  PRIMARY KEY(id)
);

CREATE TABLE PASSPORT.location (
    id integer GENERATED ALWAYS as IDENTITY (
        START
        with
            1 INCREMENT by 1
    ),
    nation varchar(50),
    city varchar(50),
    district varchar(50),
    PRIMARY KEY (id)
)

ALTER TABLE resident
ADD CONSTRAINT fk_res_loca FOREIGN KEY (locationId) REFERENCES passport.location (id);

ALTER TABLE userRequest
ADD CONSTRAINT fk_uReq_loca FOREIGN KEY (locationId) REFERENCES passport.location (id);

ALTER TABLE passport
ADD CONSTRAINT fk_pp_res FOREIGN KEY (residentId) REFERENCES resident (id);

ALTER TABLE employee
ADD CONSTRAINT fk_emp_res FOREIGN KEY (residentId) REFERENCES resident (id);

CREATE VIEW passportDetails (
    passportID,
    fullName,
    CCCD,
    gender,
    phone,
    email,
    nation,
    city,
    district,
    startDate,
    endDate
) AS
SELECT p.passportID, r.fullName, r.CCCD, r.gender, r.phone, r.email, l.nation, l.city, l.district, p.startDate, p.endDate
FROM
    resident r
    JOIN passport p ON r.id = p.residentId
    JOIN location l ON r.locationId = l.id;

SELECT * FROM passportDetails;

-- run this if u get fuck with data
--DROP TABLE employee;
--DROP TABLE userRequest;
--DROP TABLE passport;
--DROP TABLE resident;
--DROP TABLE location;
--
--TRUNCATE TABLE employee;
--TRUNCATE TABLE userRequest;
--TRUNCATE TABLE passport;
--TRUNCATE TABLE resident;
--TRUNCATE TABLE location;